category/urls.py
#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from category.views import CategoryListView, CategoryCreateView
from category.views import CategoryDetailView, CategoryUpdateView
from category.views import TagListView, TagDetailView
from category.views import TagCreateView, TagUpdateView

from category.api import CategoryViewSet, TagViewSet

from rest_framework import routers
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(
        r'^category/$',
        CategoryListView.as_view(),
        name="category-home"
        ),
    url(
        r'^category/page/(?P<page>\w+)/$',
        CategoryListView.as_view(),
        name="category-home-paginated"
    ),
    url(
        r'^category/add/$',
        CategoryCreateView.as_view(),
        name="category-add"
    ),
    url(r'^category/id/(?P<pk>\d+)/$',
        CategoryDetailView.as_view(), name="category-detail"),
    url(r'^category/name/(?P<slug>[-\w]+)/$',
        CategoryDetailView.as_view(), name="category-detail"),
    url(
        r'^category/(?P<pk>\d+)/update$',
        CategoryUpdateView.as_view(),
        name="category-update"
    ),
    url(
        r'^category/(?P<slug>\w+)/update$',
        CategoryUpdateView.as_view(),
        name="category-update"
    ),
]

urlpatterns += [
    url(
        r'^tag /$',
        TagListView.as_view(),
        name="tag-home"
    ),
    url(
        r'^tag/page/(?P<page>\w+)/$',
        TagListView.as_view(),
        name="tag-home-paginated"
    ),
    url(
        r'^tag/add/$',
        TagCreateView.as_view(),
        name="tag-add"
    ),
    url(
        r'^tag/(?P<slug>[\w-]+)/$',
        TagDetailView.as_view(),
        name="tag-detail"
    ),
    url(
        r'^tag/(?P<id>\d+)/update/$',
        TagUpdateView.as_view(),
        name="tag-update"
    ),
]


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter(trailing_slash=False)
router.register(r'category', CategoryViewSet, base_name="api_category")
router.register(r'tag', TagViewSet, base_name="api_tag")

urlpatterns += [
    url(r'^api/', include(router.urls)),
    url(r'^docs/', include_docs_urls(title='Category API'))
]

oldcategory/urls.py
#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns, include

from category.views import CategoryListView, CategoryCreateView, CategoryDetailView, CategoryUpdateView
from category.views import TagListView, TagDetailView, TagCreateView, TagUpdateView


urlpatterns = patterns('',
    url(r'^category/$', CategoryListView.as_view(), name="category-home"),
    url(r'^category/page/(?P<page>\w+)/$', CategoryListView.as_view(), name="category-home-paginated"),
    url(r'^category/add/$', CategoryCreateView.as_view(), name="category-add"),
    url(r'^category/(?P<slug>\w+)/$', CategoryDetailView.as_view(), name="category-view"),
    url(r'^category/(?P<slug>\w+)/update$', CategoryUpdateView.as_view(), name="category-update"),
)

urlpatterns += patterns('',
    url(r'^tag /$', TagListView.as_view(), name="tag-home"),
    url(r'^tag/page/(?P<page>\w+)/$', TagListView.as_view(), name="tag-home-paginated"),
    url(r'^tag/add/$', TagCreateView.as_view(), name="tag-add"),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name="tag-view"),
    url(r'^tag/(?P<id>\d+)/update/$', TagUpdateView.as_view(), name="tag-update"),
)

category/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

import logging

logger = logging.getLogger(__name__)


class TagManager(models.Manager):
    """
    Manager for `Tag` objects.
    """

    def get_by_natural_key(self, slug):
        """
        get Tag by natural key, to allow serialization by key rather than `pk`
        """
        return self.get(slug=slug)


@python_2_unicode_compatible
class Tag(models.Model):
    """
    A tag.
    """

    objects = TagManager()
    """
    Overwrite the inherited manager with the
    custom :mod:`feeds.models.TagManager`
    """

    name = models.CharField(
        _('name'),
        max_length=50,
        unique=True,
        db_index=True
    )
    """The name of the Tag."""

    slug = models.SlugField(
        max_length=255,
        db_index=True,
        unique=True,
        help_text='Short descriptive unique name for use in urls.',
    )
    """
    The slug of the Tag.
    It can be used in any URL referencing this particular Tag.
    """

    relevant = models.BooleanField(default=False)
    """
    Indicates whether this Tag is relevant for further processing.
    It should be used to allow administrative intervention.
    """

    touched = models.DateTimeField(auto_now=True)
    """Keep track of when this Tag was last used."""

    content_type = models.ForeignKey(
        ContentType,
        null=True,
        on_delete=models.CASCADE
    )
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    @classmethod
    def create(cls, name, slug=None):
        tag = cls(name=name)
        if not slug:
            tag.slug = slugify(tag.name)
        tag.save()
        logger.debug("Tag name, slug: %s, %s" % (tag.name, tag.slug))
        return tag

    class Meta:
        """
        Django Meta.
        """
        ordering = ('name',)
        verbose_name = _('tag')
        verbose_name_plural = _('tags')

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == "":
            self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        """
        Human readable representation of the object.
        """
        return u''.join(self.name)

    def natural_key(self):
        return u''.join(self.slug)

    @models.permalink
    def get_absolute_url(self):
        return ('category:tag-view', [str(self.slug)])


class CategoryManager(models.Manager):
    """
    Manager for Category
    """
    def get_by_natural_key(self, slug):
        """
        Get Category by natural kea to allow serialization
        """
        return self.get(slug=slug)


@python_2_unicode_compatible
class Category(models.Model):
    """
    Category model to be used for categorization of content. Categories are
    high level constructs to be used for grouping and organizing content,
    thus creating a site's table of contents.
    """
    objects = CategoryManager()

    name = models.CharField(
        max_length=200,
        unique=True,
        help_text='Short descriptive name for this category.',
    )

    slug = models.SlugField(
        max_length=255,
        db_index=True,
        unique=True,
        help_text='Short descriptive unique name for use in urls.',
    )

    parent = models.ForeignKey('self', null=True, blank=True)

    class Meta:
        """
        Django Meta.
        """
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    @property
    def children(self):
        return self.category_set.all().order_by('name')

    @classmethod
    def create(cls, name, slug=None):
        cat = cls(name=name)
        if not slug:
            cat.slug = slugify(cat.name)
        cat.save()
        logger.debug("Category name, slug: %s, %s" % (cat.name, cat.slug))
        return cat

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == "":
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        """
        Human readable representation of the object.
        """
        return u''.join(self.name)

    def natural_key(self):
        return u''.join(self.slug)

    @models.permalink
    def get_absolute_url(self):
        return ('category:category-view', [str(self.slug)])

category/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms.layout import Fieldset
from crispy_forms.layout import ButtonHolder
from crispy_forms.layout import Submit
from crispy_forms.layout import Button
from crispy_forms.layout import Div


from .models import Category, Tag


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'parent',)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'name',
                'parent',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='btn-small'),
                Button('cancel', 'Cancel', css_class='btn-small')
            )
        )
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-inline'
        self.helper.form_action = 'planet:category-add'
        super(CategoryCreateForm, self).__init__(*args, **kwargs)


class CategoryUpdateForm(forms.ModelForm):
    """
    CategoryUpdateForm

    Django Form to modify an angryplanet-category

    ..author: Andreas Neumeier
    """
    class Meta:
        model = Category
        fields = ('name', 'slug', 'parent',)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Change Category',
                'name',
                'slug',
                'parent',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='btn-small'),
                Button('cancel', 'Cancel', css_class='btn-small')
            )
        )
        self.helper.form_method = 'post'
        super(CategoryUpdateForm, self).__init__(*args, **kwargs)


class TagCreateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name', )


class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'parent',)

oldcategory/forms.py
from django import forms
from models import Category, Tag

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'parent',)
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'title', 
                'parent',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='btn-small'),
                Button('cancel', 'Cancel', css_class='btn-small')
            )
        )
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-inline'
        self.helper.form_action = 'planet:category-add'
        super(CategoryCreateForm, self).__init__(*args, **kwargs)

class CategoryUpdateForm(forms.ModelForm):
    """
    CategoryUpdateForm

    Django Form to modify an angryplanet-category

    ..author: Andreas Neumeier
    """
    class Meta:
        model = Category
        fields = ('title', 'slug', 'parent',)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Change Category',
                'title',
                'slug',
                'parent',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='btn-small'),
                Button('cancel', 'Cancel', css_class='btn-small')
            )
        )
        self.helper.form_method = 'post'
        super(CategoryUpdateForm, self).__init__(*args, **kwargs)

class TagCreateForm(forms.ModelForm):
  class Meta:
    model = Tag
    fields = ('name', )

class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category

category/views.py
#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

"""
"""

from django.core.urlresolvers import reverse
from django.views.generic import CreateView, UpdateView
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Category, Tag
from .forms import CategoryCreateForm, TagCreateForm, CategoryUpdateForm


class CategoryListView(ListView):
    """
    List all registered feeds

    """
    model = Category
    context_object_name = "categories"
    paginate_by = 10


class CategoryDetailView(LoginRequiredMixin, DetailView):
    """
    Show details for a particular Category

    .. ToDo::
    this shall include stats
    """
    model = Category


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    """
    Update a particular Category
    """
    permission_required = "category.update_category"
    form_class = CategoryUpdateForm
    model = Category

    def get_success_url(self):
        if 'slug' in self.kwargs:
            return reverse('category:category-view', self.kwargs['slug'])
        else:
            return reverse('category:category-home')


class CategoryCreateView(LoginRequiredMixin, CreateView):
    """
    ToDo:
    make this more nice & userfriendly
    """
    form_class = CategoryCreateForm
    model = Category
    initial = {'is_Active': False}


class TagListView(ListView):
    """
    List all registered tags

    """
    model = Tag
    context_object_name = "tags"
    paginate_by = 10
    queryset = Tag.objects.all()


class TagDetailView(DetailView):
    """
    Show details for a particular tag.

    ToDo:
    this shall include stats
    """
    model = Tag
    paginate_by = 10


class TagCreateView(LoginRequiredMixin, CreateView):
    """
    ToDo:
    make this more nice & userfriendly
    """
    form_class = TagCreateForm
    model = Tag
    initial = {'is_Active': False}


class TagUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Update particular tag
    """
    permission_required = "category.update_tag"
    model = Tag

oldcategory/views.py
#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

"""
"""

from django.views.generic import CreateView, UpdateView
from django.views.generic import DetailView, ListView
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from models import Category, Tag
from forms import CategoryCreateForm, TagCreateForm, CategoryUpdateForm

class CategoryListView(ListView):
    """
    List all registered feeds

    """
    model = Category
    context_object_name = "categories"
    paginate_by = 10

class CategoryDetailView(DetailView):
    """
    Show details for a particular Category

    ToDo:
    this shall include stats
    """
    model = Category

    def dispatch(self, *args, **kwargs):
        return super(CategoryDetailView, self).dispatch(*args, **kwargs)

class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    """
    Update a particular Category
    """
    form_class = CategoryUpdateForm
    model = Category

    def get_success_url(self):
        if 'slug' in self.kwargs:
            return reverse('planet:category-view', self.kwargs['slug'])
        else:
            return reverse('planet:category-home')

class CategoryCreateView(LoginRequiredMixin, CreateView):
    """
    ToDo:
    make this more nice & userfriendly
    """
    form_class = CategoryCreateForm
    model = Category
    initial = {'is_Active': False}

class TagListView(ListView):
    """
    List all registered tags

    """
    model = Tag
    context_object_name = "tags"
    paginate_by = 10
    queryset = Tag.objects.all()

class TagDetailView(DetailView):
    """
    Show details for a particular tag.

    ToDo:
    this shall include stats
    """
    model = Tag
    paginate_by = 10

    def dispatch(self, *args, **kwargs):
        return super(TagDetailView, self).dispatch(*args, **kwargs)

class TagCreateView(LoginRequiredMixin, CreateView):
    """
    ToDo:
    make this more nice & userfriendly
    """
    form_class = TagCreateForm
    model = Tag
    initial = {'is_Active': False}

class TagUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Update particular tag
    """
    permission_required = "feeds.update_tag"
    model = Tag

oldcategory/templates/category/category_detail.html
{%extends 'feeds/index.html'%}

{%block breadcrumb %}
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:feed-home" %}">Feeds</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:category-home" %}">Categories</a> <span class="divider">/</span></li>
            {% if object %}<li><a href="{% url "planet:category-view" object.slug %}">{{ object.title }}</a> <span class="divider">/</span></li>{% endif %}
            <li class="active">You are here</li>
          </ul>
{%endblock%}

{%block content%}
<div class="row">
    <div class="span4">
        <h3>
            {{object}}
            {% if user.is_authenticated %}
              {% if perms.feeds.change_category %}<a href="{{object.get_absolute_url}}update" class="btn btn-mini category-tooltip" title="edit category"><i class="icon-edit"></i></a>{% endif %}
              {% if perms.feeds.delete_category %}<a href="{{object.get_absolute_url}}delete" class="btn btn-mini category-tooltip" title="delete category"><i class="icon-trash"></i></a>{% endif %}
            {% endif %}
        </h3>
    </div>
    <div class="span7">
        <table class="table table-condensed table-hover">
            <tr>
                <td>Feed</td>
                <td>Posts</td>
                {% if user.is_authenticated %}
                <td>Options</td>
                {% endif %}
            </tr>
            {% for feed in object.feeds %}
            <tr>
                <td><a href="{{ feed.get_absolute_url }}">{{ feed }}</a></td>
                <td>{{ feed.posts.count }}</td>
                {% if user.is_authenticated %}
                <td>
                  <a href="{{ feed.get_absolute_url }}" class="btn btn-mini category-tooltip" title="Go to feed"><i class="icon-step-forward"></i></a>
                    {% if perms.feeds.change_feed %}<a href="{{o.get_absolute_url}}update" class="btn btn-mini category-tooltip" title="edit feed"><i class="icon-edit"></i></a>{% endif %}
                    {% if perms.feeds.delete_feed %}<a href="{{o.get_absolute_url}}delete" class="btn btn-mini category-tooltip" title="delete feed"><i class="icon-trash"></i></a>{% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{%endblock%}


{% block additional_scripts_end %}
    <script defer src="{{ STATIC_URL }}feeds/category_detail.js"> </script>
{% endblock %}

oldcategory/templates/category/category_form.html
{%extends 'feeds/index.html'%}
{% load crispy_forms_tags %}
{%block content%}
{% crispy form %}
{%endblock%}

oldcategory/templates/category/category_list.html
{%extends 'feeds/index.html'%}

{%block breadcrumb %}
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:feed-home" %}">Feeds</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:category-home" %}">Categories</a> <span class="divider">/</span></li>
            <li class="active">You are here</li>
          </ul>
{%endblock%}

{% block content %}
<table class="table table-striped table-condensed">
{%for o in object_list%}
  <tr>
    <td><a href="{{ o.get_absolute_url }}">{{ o }}</a></td>
    <td>{{o.post_set.count}}</td>
    <td>
   {% if user.is_authenticated %}
     {% if perms.feeds.edit_category %}<a href="{{o.get_absolute_url}}update" class="btn btn-mini">edit</a>{% endif %}
     {% if perms.feeds.delete_category %}<a href="{{o.get_absolute_url}}delete" class="btn btn-mini">delete</a>{% endif %}
   {% endif %}
     </td>
  </tr>
{% endfor %}
</table>

{% if is_paginated %}
  <div class="pagination pagination-mini pagination-centered">
    <ul>
      {% if page_obj.has_previous %}
        <li class="active"><a href="{% url "planet:category-home-paginated" page_obj.previous_page_number %}"> previous</a></li>
      {% else %}
        <li class="disabled"><a href="#">previous</a></li>
      {% endif %}

      {% for page in  page_obj.paginator.page_range %}
        {% if page == page_obj.number %}
          <li class="disabled"><a href="#">{{ page }}</a></li>
        {% else %}
          <li class="active"><a href="{% url "planet:category-home-paginated" page %}">{{ page }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="active"> <a href="{% url "planet:category-home-paginated" page_obj.next_page_number %}">next</a></li>
      {% else %}
        <li class="disabled"><a href="#">next</a></li>
      {% endif %}
    </ul>
  </div>
{% endif %}

{%endblock%}

oldcategory/templates/category/index.html
{% extends "base3.html" %}

{%block breadcrumb %}
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="{% url "category:home" %}">Categories</a> <span class="divider">/</span></li>
            <li class="active">You are here</li>
          </ul>
{%endblock%}

{%block content%}
{%endblock%}

{% block additional_scripts_end %}
{% endblock %}

oldcategory/templates/category/tag_detail.html
{%extends 'feeds/index.html'%}

{%block breadcrumb %}
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:feed-home" %}">Feeds</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:tag-home" %}">Tags</a> <span class="divider">/</span></li>
            {% if object %}<li><a href="{% url "planet:tag-view" object.slug %}">{{ object.name }}</a> <span class="divider">/</span></li>{% endif %}
            <li class="active">You are here</li>
          </ul>
{%endblock%}

{%block content%}
<div class="row">
    <div class="span4">
        <h3>
            {{object}}
            {% if user.is_authenticated %}
              {% if perms.feeds.change_tag %}<a href="{{object.get_absolute_url}}update" class="btn btn-mini tag-tooltip" title="edit tag"><i class="icon-edit"></i></a>{% endif %}
              {% if perms.feeds.delete_tag %}<a href="{{object.get_absolute_url}}delete" class="btn btn-mini tag-tooltip" title="delete tag"><i class="icon-trash"></i></a>{% endif %}
            {% endif %}
        </h3>
    </div>
    <div class="span7">
        <table class="table table-condensed table-hover">
            <tr><td>Article</td><td>Options</td></tr>
            {% for post in object.posts %}
            <tr>
                {% if user.is_authenticated %}
                    <td><a href="{{ post.get_absolute_url }}">{{ post }}</a></td>
                {% else %}
                    <td>{{ post }}</td>
                {% endif %}
                <td>
    {% if user.is_authenticated %}
      <a href="{{ post.get_absolute_url }}" class="btn btn-mini tag-tooltip" title="Go to Post"><i class="icon-step-forward"></i></a>
    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{%endblock%}


{% block additional_scripts_end %}
    <script defer src="{{ STATIC_URL }}feeds/tag_detail.js"> </script>
{% endblock %}

oldcategory/templates/category/tag_form.html
{%extends 'feeds/index.html'%}
{% load crispy_forms_tags %}
{%block content%}
{% crispy form %}
{%endblock%}

oldcategory/templates/category/tag_list.html
{%extends 'feeds/index.html'%}

{%block breadcrumb %}
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:feed-home" %}">Feeds</a> <span class="divider">/</span></li>
            <li><a href="{% url "planet:tag-home" %}">Tags</a> <span class="divider">/</span></li>
            <li class="active">You are here</li>
          </ul>
{%endblock%}

{% block content %}
<table class="table table-striped table-condensed">
{%for o in object_list%}
  <tr>
    <td><a href="{{o.get_absolute_url}}">{{ o }}</a></td>
    <td>
    {% if user.is_authenticated %}
      {% if perms.feeds.change_tag %}<a href="{{o.get_absolute_url}}update" class="btn btn-mini"><i class="icon-edit"></i></a>{% endif %}
      {% if perms.feeds.delete_tag %}<a href="{{o.get_absolute_url}}delete" class="btn btn-mini"><i class="icon-trash"></i></a>{% endif %}
    {% endif %}
    </td>
  </tr>
{% endfor %}
</table>

{% if is_paginated %}
  <div class="pagination pagination-mini pagination-centered">
    <ul>
      {% if page_obj.has_previous %}
        <li class="active"><a href="{% url "planet:tag-home-paginated" page_obj.previous_page_number %}"> previous</a></li>
      {% else %}
        <li class="disabled"><a href="#">previous</a></li>
      {% endif %}

      {% for page in  page_obj.paginator.page_range %}
        {% if page == page_obj.number %}
          <li class="disabled"><a href="#">{{ page }}</a></li>
        {% else %}
          <li class="active"><a href="{% url "planet:tag-home-paginated" page %}">{{ page }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="active"> <a href="{% url "planet:tag-home-paginated" page_obj.next_page_number %}">next</a></li>
      {% else %}
        <li class="disabled"><a href="#">next</a></li>
      {% endif %}
    </ul>
  </div>
{% endif %}

{%endblock%}